### PR TITLE
Add `Deploy to Swifton.me`-Badge

### PR DESCRIPTION
**Pull request by kimar**
My open-source project `Swifton.me` is a lightweight and hassle-free Heroku-like Swift PaaS.
I'd like to add this Badge to let users try it out without registration etc.

See https://serve.swifton.me for more infos.

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
@kimar thanks, very interesting coincidence to come up with so similar name :) Did you try to deploy TodoApp on your service and is everything ok?

**Comment by DK1DA** [comment]
Hi @sauliusgrigaitis,

yeah indeed. Started working on that when  first made Swift open source. Yeah it's working fine for me. Did you try clicking the button? It should work ootb.

**Comment by DK1DA** [comment]
Just deployed it here: http://nostalgic-albattani.serve.swifton.me/todos

**Comment by DK1DA** [comment]
You can use the click the button, if you want to see what's going on during deployment just head to https://serve.swifton.me/{id-from-url}/logs and you'll see the app's STDOUT

**Comment by sauliusgrigaitis** [comment]
Cool. Thanks!

**Pull request merged**
